# Generated by Django 5.1 on 2024-09-03 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_category_options_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='Topic',
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name_plural': '   Topics'},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='categories',
            new_name='Topic',
        ),
    ]
